import "./globals.css";
import type { Metadata } from "next";
import { Familjen_Grotesk } from "next/font/google";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

const familjenGrotesk = Familjen_Grotesk({
   subsets: ["latin"],
   variable: "--font-familjen-grotesk",
});

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en" className={familjenGrotesk.variable}>
         <body>{children}</body>
      </html>
   );
}
